In [1]:
import numpy as np
import plotly.graph_objects as go
from matplotlib.pyplot import title

In [2]:
X = np.array([[1, 2], [2, 4], [3, 6], [4, 8]])
y = np.array([5,9,13,17])

X_with_intercept = np.hstack([np.ones((X.shape[0], 1)), X])

lambda_ridge = 0.1
I = np.eye(X_with_intercept.shape[1])
beta_ridge = np.linalg.inv(X_with_intercept.T @ X_with_intercept + lambda_ridge * I) @ X_with_intercept.T @ y


In [3]:
x1_range = np.linspace(0, 5, 20)
x2_range = 2 * x1_range
x1_mesh, x2_mesh = np.meshgrid(x1_range, x2_range)
Y_mesh = beta_ridge[0] + beta_ridge[1] * x1_mesh + beta_ridge[2] * x2_mesh


In [4]:
fig = go.Figure(data=[go.Scatter3d(x=X[:, 0], y=X[:,1], z=y, mode='markers', marker=dict(size=5, color='red')), go.Surface(x=x1_mesh, y=x2_mesh, z=Y_mesh,opacity=0.5)])
fig.update_layout(scene=dict(xaxis_title='X1', yaxis_title='X2', zaxis_title='Y'), title='Ridge Regression in 3D Hyperplane')
fig.show()

In [5]:
beta_ridge

array([0.90460099, 0.80582272, 1.61164544])

In [9]:
beta0 = beta_ridge[0]
beta1 = beta_ridge[1]
beta2 = beta_ridge[2]

In [10]:
X_1 = np.array([1,2,3,4])
X_2 = 2 * X_1

h_x = beta0 + beta1 * X_1 + beta2 * X_2

In [11]:
h_x

array([ 4.93371458,  8.96282818, 12.99194177, 17.02105537])

In [12]:
y

array([ 5,  9, 13, 17])